/* Farbatlas V10: getrennte Bildspeicherung */
(()=>{
const q=s=>document.querySelector(s);let v10Name='',v10Password='';
async function v10api(action,data={}){const r=await fetch('/api/farbatlas',{method:'POST',headers:{'content-type':'application/json',...(adminToken?{authorization:'Bearer '+adminToken}:{})},body:JSON.stringify({action,...data})});const t=await r.text();let b;try{b=JSON.parse(t)}catch{b={error:t||('HTTP '+r.status)}}if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b}
function meta(){return{version:10,app:document.title,images:records.filter(r=>!r.name.startsWith('dummy_')).map(r=>{const x=imported.find(i=>i.name===r.name);return{name:r.name,imageKey:x?.imageKey||r.imageKey||null}}),savedGroups,groupMoves,recordEdits,titleImages,deleted:[...deletedRecords]}}
const imageFrom=s=>new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=s});
async function shrink(src){const im=await imageFrom(src);let max=1800,q=.82;for(let n=0;n<6;n++){const z=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*z));c.height=Math.max(1,Math.round(im.height*z));c.getContext('2d').drawImage(im,0,0,c.width,c.height);const d=c.toDataURL('image/jpeg',q),b=d.split(',')[1];if(Math.ceil(b.length*3/4)<3500000)return{data:b,type:'image/jpeg'};max=Math.round(max*.78);q=Math.max(.52,q-.07)}throw new Error('Ein Bild konnte nicht ausreichend verkleinert werden.')}
async function uploadAll(name,password,st){const pending=imported.filter(x=>!x.imageKey);for(let i=0;i<pending.length;i++){st.textContent=`Bild ${i+1} von ${pending.length} wird vorbereitet …`;const p=await shrink(pending[i].src);st.textContent=`Bild ${i+1} von ${pending.length} wird einzeln gespeichert …`;const u=await v10api('upload-image',{name,password,fileName:pending[i].name,type:p.type,data:p.data});pending[i].imageKey=u.imageKey}return pending.length}
async function saveV10(create){const st=q('#saveDatasetStatus'),a=q('#newDatasetBtn'),b=q('#saveDatasetBtn');try{const name=q('#saveDatasetName').value.trim(),password=q('#saveDatasetPassword').value;if(!name||!password)throw new Error('Name und Passwort sind erforderlich.');a.disabled=b.disabled=true;st.style.color='#173640';if(create){st.textContent='Datensatz wird vorbereitet …';await v10api('save',{name,password,payload:{...meta(),images:[]},create:true})}else await v10api('save',{name,password,payload:meta(),create:false});const count=await uploadAll(name,password,st);st.textContent='Datensatz wird abgeschlossen …';const r=await v10api('save',{name,password,payload:meta(),create:false});v10Name=name;v10Password=password;st.textContent=(count?`${count} Bilder wurden einzeln gespeichert. `:'')+r.message;st.style.color='#16885a'}catch(e){st.textContent=e.message;st.style.color='#c44545'}finally{a.disabled=b.disabled=false}}
async function openV10(){const st=q('#datasetStatus');try{const name=q('#openDatasetName').value.trim(),password=q('#openDatasetPassword').value;st.textContent='Datensatz wird geladen …';const r=await v10api('load',{name,password}),arr=[];for(let i=0;i<(r.payload.images||[]).length;i++){const x=r.payload.images[i];st.textContent=`Bild ${i+1} von ${r.payload.images.length} wird geladen …`;const z=await v10api('get-image',{name,password,imageKey:x.imageKey});arr.push({...x,src:`data:${z.type};base64,${z.data}`})}datasetLoaded=true;v10Name=name;v10Password=password;imported=arr;delete GROUPS.Tiere;delete GROUPS.Pflanzen;savedGroups=r.payload.savedGroups||{};delete savedGroups.Tiere;delete savedGroups.Pflanzen;groupMoves=r.payload.groupMoves||{};recordEdits=r.payload.recordEdits||{};titleImages=r.payload.titleImages||{};deletedRecords=new Set(r.payload.deleted||[]);Object.entries(savedGroups).forEach(([n,d])=>GROUPS[n]=[d.icon||'🔬',d.c1||'#68c7c2',d.c2||'#357b8c',d.families||[]]);rebuild();go([],false);st.textContent=`Datensatz „${r.name}“ wurde geöffnet.`}catch(e){st.textContent=e.message}}
function bind(){const a=q('#newDatasetBtn'),b=q('#saveDatasetBtn'),o=q('#openDatasetBtn');if(a)a.onclick=()=>saveV10(true);if(b)b.onclick=()=>saveV10(false);if(o)o.onclick=openV10;const st=q('#saveDatasetStatus');if(st&&!q('#v10hint'))st.insertAdjacentHTML('afterend','<div id="v10hint" class="hint">V10: Bilder werden beim Speichern einzeln hochgeladen. Bitte die Seite geöffnet lassen.</div>')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
